#!/bin/sh

# Roda o pytest local antes de aceitar o push
echo "> Rodando testes locais antes do push..."
pytest

# Se o pytest falhar, o código de saída será diferente de 0
if [ $? -ne 0 ]; then
 echo "> Testes falharam! Push cancelado. Corrija os erros antes de subir o código."
 exit 1
fi

echo "> Testes passaram! Enviando para o GitHub..."
exit 0